<?php

/*
 * Implements hook_permission
 */
function sample_module_permission() {
  return array(
    'administer sample module' => array(
      'title' => t('Administer Sample Module'),
      'description' => t('Configure Sample Module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sample_module_menu(){
  $items = array();
  $items['admin/config/sample-module'] = array(
    'page callback' => 'drupal_get_form', //function pag tinawag ung url (drupal_get_form() drupal function sya)
    'title' => t('Sample Module'),
    'page arguments' => array('sample_module_config_form'), //function na mag return ng drupal form array/object
    'description' => 'Configure Sample Module',
    'access arguments' => array('administer sample module'), //ung permission na ginawa nten sa hook_permission()
  );

  $items['sample-module-page'] = array(
    'page callback' => 'sample_module_page', //function pag tinawag ung url
    'title' => t('Sample Page'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['sample-module-page-with-args/%'] = array(
    'page callback' => 'sample_module_page_with_args', //function pag tinawag ung url
    'title' => t('Sample Page'),
    'page arguments' => array(1), //kung pang ilan sa url ung argument mo. 1 kasi nag start sa 0 from the left nung path
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function sample_module_config_form(){
  // sample ng pag gawa ng custom form sa drupal
  // read https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7
  // for more details :D
  $form = null;
  $form['date'] = array(
    '#type' => 'textfield',
    '#title' => 'Test'
  );
  $form['email'] = array(
    '#type' => 'submit',
    '#submit' => array('sample_module_config_form_email_submit'),
    '#value' => t('Email'));
  return system_settings_form($form);
}

function sample_module_config_form_email_submit($form, $form_state){
  $module = 'today_security_login';
  $key = 'notify';
  $language = language_default();
  $params = array();
  $from = 'test@site.com';
  $email = 'mark.cristobal@hrboss.com';
  $send = FALSE;
  $subject = 'Test subject';
  $body = array('<div class="test">test</a>', '<a href="asdfas">test123</a>');

  $message = drupal_mail($module, $key, $email, $language, $params, $from, $send);
  $message['subject'] = $subject;
  $message['body'] = $body;
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';


  // Retrieve the responsible implementation for this message.
  $system = drupal_mail_system($module, $key);


  // Format the message body.
  $message = $system->format($message);


  // Send e-mail.
  $message['result'] = $system->mail($message);
}

function sample_module_page(){
  return 'test';
}

function sample_module_page_with_args($arg){
  return $arg;
}
