<?php

/*
 * Implements hook_permission
 */
function sample_module_permission() {
  return array(
    'administer sample module' => array(
      'title' => t('Administer Sample Module'),
      'description' => t('Configure Sample Module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sample_module_menu(){  
  $items = array();
  $items['admin/config/sample-module'] = array(
    'page callback' => 'drupal_get_form', //function pag tinawag ung url (drupal_get_form() drupal function sya)
    'title' => t('Sample Module'),
    'page arguments' => array('sample_module_config_form'), //function na mag return ng drupal form array/object
    'description' => 'Configure Sample Module',
    'access arguments' => array('administer sample module'), //ung permission na ginawa nten sa hook_permission()
  );
  
  $items['sample-module-page'] = array(
    'page callback' => 'sample_module_page', //function pag tinawag ung url
    'title' => t('Sample Page'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['sample-module-page-with-args/%'] = array(
    'page callback' => 'sample_module_page_with_args', //function pag tinawag ung url
    'title' => t('Sample Page'),
    'page arguments' => array(1), //kung pang ilan sa url ung argument mo. 1 kasi nag start sa 0 from the left nung path
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function sample_module_config_form(){
  // sample ng pag gawa ng custom form sa drupal
  // read https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7
  // for more details :D
  $form = null;
  $form['date'] = array(
    '#type' => 'textfield',
    '#title' => 'Test'
  );
  return system_settings_form($form);
}

function sample_module_page(){
  return 'test';
}

function sample_module_page_with_args($arg){
  return $arg;
}